services:
  iam-server:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: iam-server
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://admin:adminpassword@postgres:5432/iam_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  # migrate:
  #   build:
  #     context: ..
  #     dockerfile: deployments/Dockerfile
  #     target: builder  # Use the Go builder stage
  #   container_name: migrate
  #   entrypoint: ["go", "run", "cmd/migrate/main.go"]
  #   environment:
  #     - DATABASE_URL=postgres://admin:adminpassword@postgres:5432/iam_db?sslmode=disable
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:15
    container_name: iam-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: iam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: iam-cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data:
