services:
  iam-server:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: iam-server
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: iam-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: iam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: iam-cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data:
