name: Build & Deploy IAM to Oracle K3s

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}/iam-server
  K8S_DEPLOYMENT: iam-server

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest -f deployments/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy to Oracle K3s
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        - name: Set up SSH connection and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying IAM Service..."
            
            # Ensure the repository exists
            if [ ! -d "~/iam-server" ]; then
              git clone https://github.com/${{ github.repository }} ~/iam-server
            fi
            
            cd ~/iam-server
            git pull origin main

            # ✅ First time deployment: Apply manifests if missing
            kubectl apply -f ~/iam-server/deployments/k8s/

            # ✅ If deployment exists, update the image
            if kubectl get deployment iam-server -n default; then
              kubectl set image deployment/iam-server iam-server=${{ env.IMAGE_NAME }}:latest -n default
              kubectl rollout status deployment/iam-server -n default
            fi
